language: python
python:
  - 2.7
  - 3.4
  - 3.5

sudo: false

# Setup anaconda following http://conda.pydata.org/docs/travis.html#the-travis-yml-file
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash ./miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  # For tests with plot instructions
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

# Install packages
install:
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION pip numpy scipy matplotlib pytest-cov
  - source activate test-environment
  - pip install .

before_script:
  - pip install coveralls

# Run test
script:
  - py.test --cov=pychebfun --cov-report=term-missing --cov-config=.coveragerc

# Calculate coverage
after_success:
  - coveralls
